# Kind Definitions

#' @export
PHYSIOLOGIC_EFFECT_KIND <- 'C6'

#' @export
DRUG_KIND <- 'C8'

#' @export
INGREDIENT_KIND <- 'C10'

#' @export
MECHANISM_OF_ACTION_KIND <- 'C12'

#' @export
PHARMACOKINETICS_KIND <- 'C14'

#' @export
DISEASE_KIND <- 'C16'

#' @export
DOSE_FORM_KIND <- 'C18'

#' @export
THERAPEUTIC_CATEGORY_KIND <- 'K20'

#' @export
ALL_KINDS <- c(
   PHYSIOLOGIC_EFFECT_KIND,
   DRUG_KIND,
   INGREDIENT_KIND,
   MECHANISM_OF_ACTION_KIND,
   PHARMACOKINETICS_KIND,
   DISEASE_KIND,
   DOSE_FORM_KIND,
   THERAPEUTIC_CATEGORY_KIND
)
