# Kind Definitions
PHYSIOLOGIC_EFFECT_KIND <- 'C6'
DRUG_KIND <- 'C8'
INGREDIENT_KIND <- 'C10'
MECHANISM_OF_ACTION_KIND <- 'C12'
PHARMACOKINETICS_KIND <- 'C14'
DISEASE_KIND <- 'C16'
DOSE_FORM_KIND <- 'C18'
THERAPEUTIC_CATEGORY_KIND <- 'K20'

ALL_KINDS <- c(
   PHYSIOLOGIC_EFFECT_KIND,
   DRUG_KIND,
   INGREDIENT_KIND,
   MECHANISM_OF_ACTION_KIND,
   PHARMACOKINETICS_KIND,
   DISEASE_KIND,
   DOSE_FORM_KIND,
   THERAPEUTIC_CATEGORY_KIND
)
